# Site settings
title: Hayder Tirmazi
description: Mathematician and Cryptographer researching theoretical computer science, cryptography, and privacy-preserving data structures
author: Hayder Tirmazi
email: hayder.research@gmail.com

# Build settings
markdown: kramdown
theme: minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO settings
social:
  name: Hayder Tirmazi
  links:
    - https://scholar.google.com/citations?user=qgOBcYMAAAAJ
    - https://github.com/jadidbourbaki

# Site configuration
show_downloads: false
google_analytics: G-K4F6FRWCSL
lang: en
encoding: UTF-8

# Jekyll settings
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - LICENSE

# Custom variables
institution: City College of New York
research_interests:
  - Theoretical Computer Science
  - Cryptography
  - Privacy-Preserving Data Structures
  - Computational Complexity
