# Site settings
title: Hayder Tirmazi
description: Mathematician and Cryptographer
author: Hayder Tirmazi

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Site configuration
show_downloads: false
google_analytics: G-K4F6FRWCSL
lang: en
encoding: UTF-8

# Jekyll settings
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - LICENSE
